services:
  hibernate-learn-postgres:
    image: postgres:16.2
    volumes:
      - hibernate-learn-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  hibernate-learn-postgres_data: